export enum Configuration{
  DB_HOST='DB_HOST',
  DB_USERNAME='DB_USERNAME',
  DB_PORT='DB_PORT',
  DB_NAME='DB_NAME',
  DB_PASSWORD='DB_PASSWORD',
  DB_TYPE='DB_TYPE',

  PORT='PORT',

  API_PREFIX='API_PREFIX',
  API_VERSION='API_VERSION'
}
